# Applying Machine Learning to Sentiment Analysis

Source: http://ai.stanford.edu/~amaas/data/sentiment/

In [1]:
import pyprind
import pandas as pd
import os

reload_data = True

In [2]:
if reload_data:
    pbar = pyprind.ProgBar(50000)
    labels = {'pos':1, 'neg':0}
    df = pd.DataFrame()
    for s in ('test', 'train'):
        for l in ('pos', 'neg'):
            path ='./downloads/aclImdb/%s/%s' % (s, l)
            for file in os.listdir(path):
                with open(os.path.join(path, file), 'r', encoding="utf8") as infile:
                    txt = infile.read()
                df = df.append([[txt, labels[l]]], ignore_index=True)
                pbar.update()

    df.columns = ['review', 'sentiment']

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:02:56


In [3]:
if reload_data:
    df.to_csv('./downloads/aclImdb/movie_data.csv', index=False, encoding='utf8')

In [4]:
df = pd.read_csv('./downloads/aclImdb/movie_data.csv', encoding='utf8')
print(df.head())

import numpy as np

np.random.seed(0)
df = df.reindex(np.random.permutation(df.index))

                                              review  sentiment
0  Gorgeous Annie Belle in her prime stars in thi...          1
1  How is bear´s paw, elephant´s trunk or monkey´...          1
2  The Regard of Flight, written and performed by...          1
3  Based on an actual story, John Boorman shows t...          1
4  To solve a challenging problem, you need to st...          1


### Bag of words concept

In [5]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
count = CountVectorizer()
docs = np.array(['The sun is shining', 'The water is sweet', 'The sun is shining and the water is sweet'])
bag = count.fit_transform(docs)

In [6]:
print(count.vocabulary_)

{'sun': 3, 'is': 1, 'water': 6, 'shining': 2, 'the': 5, 'sweet': 4, 'and': 0}


In [7]:
print(bag.toarray())

[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [8]:
# inverse document frequency and the importance of words/tokens
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[ 0.          0.43370786  0.55847784  0.55847784  0.          0.43370786
   0.        ]
 [ 0.          0.43370786  0.          0.          0.55847784  0.43370786
   0.55847784]
 [ 0.40474829  0.47810172  0.30782151  0.30782151  0.30782151  0.47810172
   0.30782151]]


In [9]:
# data cleansing
import re
def preprocessor(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text)
    text = re.sub('[\W]+', ' ', text.lower()) + ' '.join(emoticons).replace('-', '')
    return text

preprocessor("</a>This :) is :( a test :-)!")

'this is a test :) :( :)'

In [10]:
df['review'] = df['review'].apply(preprocessor)

In [11]:
def tokenizer(text):
    return text.split()
tokenizer('runners like running and thus they run')

['runners', 'like', 'running', 'and', 'thus', 'they', 'run']

In [12]:
from nltk.stem.porter import PorterStemmer
porter = PorterStemmer()
def tokenizer_porter(text):
    #return [porter.stem(word) for word in text.split()]
    return pd.Series(text.split()).apply(porter.stem).tolist()
tokenizer_porter('runners like running and thus they run')

['runner', 'like', 'run', 'and', 'thu', 'they', 'run']

In [13]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/grzegorz/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [14]:
from nltk.corpus import stopwords
stop = stopwords.words('english')
[w for w in tokenizer_porter('a runner likes running and runs a lot')[-10:] if w not in stop]

['runner', 'like', 'run', 'run', 'lot']

In [15]:
X_train = df.loc[:25000, 'review'].values
y_train = df.loc[:25000, 'sentiment'].values
X_test = df.loc[25000:, 'review'].values
y_test = df.loc[25000:, 'sentiment'].values

In [16]:
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
import tokenizers
import pickle

estimate = True

if estimate:
    param_grid = [{'vect__ngram_range': [(1,1)],
                   'vect__stop_words': [stop, None],
                   'vect__tokenizer': [tokenizers.tokenizer, 
                                       tokenizers.tokenizer_porter],
                   'clf__penalty': ['l1', 'l2'],
                   'clf__C': [1.0, 10.0, 100.0]},
                  {'vect__ngram_range': [(1,1)],
                   'vect__stop_words': [stop, None],
                   'vect__tokenizer': [tokenizers.tokenizer, 
                                       tokenizers.tokenizer_porter],
                   'vect__use_idf':[False],
                   'vect__norm':[None],
                   'clf__penalty': ['l1', 'l2'],
                   'clf__C': [1.0, 10.0, 100.0]}]

    lr_tfidf = Pipeline([('vect', TfidfVectorizer(strip_accents=None, 
                                                  lowercase=False, 
                                                  preprocessor=None)),
                         ('clf', LogisticRegression(random_state=0))])
    gs_lr_tfidf = GridSearchCV(lr_tfidf, param_grid, 
                               scoring='accuracy',
                               cv=5, verbose=1,
                               n_jobs=4)

    gs_lr_tfidf.fit(X_train, y_train)
    
    with open('gs_lr_tfidf', 'wb') as f:
        pickle.dump(gs_lr_tfidf, f, pickle.HIGHEST_PROTOCOL)
else:
    with open("gs_lr_tfidf", "rb") as f:
        gs_lr_tfidf = pickle.load(f)

Fitting 5 folds for each of 48 candidates, totalling 240 fits


[Parallel(n_jobs=4)]: Done  42 tasks      | elapsed: 80.8min
[Parallel(n_jobs=4)]: Done 192 tasks      | elapsed: 3124.2min
[Parallel(n_jobs=4)]: Done 240 out of 240 | elapsed: 3215.5min finished


In [17]:
from sklearn.metrics import accuracy_score
accuracy_score(gs_lr_tfidf.predict(X_test), y_test)

0.8938517240212499

In [18]:
gs_lr_tfidf.predict(['I like this movie'])

array([0])

In [19]:
gs_lr_tfidf.best_params_

{'clf__C': 10.0,
 'clf__penalty': 'l2',
 'vect__ngram_range': (1, 1),
 'vect__stop_words': None,
 'vect__tokenizer': <function tokenizers.tokenizer>}

In [20]:
gs_lr_tfidf.best_score_

0.88932902973395933

In [21]:
gs_lr_tfidf.score(X_test, y_test)

0.8938517240212499

## Working with bigger data – online algorithms and out-of-core learning

In [22]:
import numpy as np
import re
from nltk.corpus import stopwords
stop = stopwords.words('english')

def tokenizer(text):
    text = re.sub('<[^>]*>', '', text)
    emoticons = re.findall('(?::|;|=)(?:-)?(?:\)|\(|D|P)', text.lower())
    text = re.sub('[\W]+', ' ', text.lower()) + ' '.join(emoticons).replace('-', '')
    tokenized = [w for w in text.split() if w not in stop]
    return tokenized

tokenizer('tralalala:)')

['tralalala', ':)']

In [23]:
def stream_docs(path):
    with open(path, 'r', encoding='utf8') as csv:
        next(csv) # skip header
        for line in csv:
            text, label = line[:-3], int(line[-2])
            yield text, label

In [24]:
sd = stream_docs(path='./downloads/aclImdb/movie_data.csv')
print(next(sd))
print(next(sd))

('"Gorgeous Annie Belle in her prime stars in this adventure/sex movie. She wears her hair in a buzz cut that is bleached platinum. She and her boyfriend are visiting some tropical Asian paradise. They have decided to keep an ""open"" sexual relationship, which is played out on their journey to find a secret society/tribe where the people live one year and then are reborn in some kind of ceremony. The scenery is gorgeous, deep vast green gorges and jungles are explored. The imagery is very similar to that of the movie ""Black Emanuelle"". It is rich and colorful. Recommended!"', 1)
('"How is bear´s paw, elephant´s trunk or monkey´s brain for dinner? Let Tsui Hark tell you in this wonderful and lighthearted comedy about the art of cooking the traditional(?) Chinese way.<br /><br />This movie shares the common structure of an American sports movie, but instead of focusing on baseball it centers around cooking which makes it all the more interesting. I even think Leslie Cheung´s character

In [25]:
def get_minibatch(doc_stream, size):
    docs, y = [], []
    try:
        for _ in range(size):
            text, label = next(doc_stream)
            docs.append(text)
            y.append(label)
    except StopIteration:
        return None, None
    return docs, y

In [26]:
np.random.seed()
df = df.reindex(np.random.permutation(df.index))
df.to_csv('./downloads/aclImdb/movie_data_unsorted.csv', index=False, encoding='utf8')

In [27]:
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import SGDClassifier

vect = HashingVectorizer(decode_error='ignore', 
                         n_features=2**21, 
                         preprocessor=None,
                         tokenizer=tokenizer)
clf = SGDClassifier(loss='log', n_iter=1)
doc_stream = stream_docs(path='./downloads/aclImdb/movie_data_unsorted.csv')

In [28]:
import pyprind

pbar = pyprind.ProgBar(45)
classes = np.array([0, 1])

for _ in range(45):
    X_train, y_train = get_minibatch(doc_stream, size=1000)
    if not X_train:
        break
    X_train = vect.transform(X_train)
    clf.partial_fit(X_train, y_train, classes=classes)
    pbar.update()

0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:30


In [29]:
X_test, y_test = get_minibatch(doc_stream, size=5000)
X_test = vect.transform(X_test)
print('Accuracy: %.3f' % clf.score(X_test, y_test))

Accuracy: 0.873


In [30]:
clf = clf.partial_fit(X_test, y_test)

In [31]:
clf.predict_proba(vect.transform(['I love it']))

array([[ 0.08967493,  0.91032507]])

### Chapter 9: Serializing objects

In [32]:
import pickle
import os

dest = os.path.join('movieclassifier', 'pkl_objects')
if not os.path.exists(dest):
    os.makedirs(dest)
#pickle.dump(stop, open(os.path.join(dest, 'stopwords.pkl'),'wb'), protocol=4)
pickle.dump(clf, open(os.path.join(dest, 'classifier.pkl'), 'wb'), protocol=4)
#pickle.dump(gs_lr_tfidf, open(os.path.join(dest, 'classifier_large.pkl'), 'wb'), protocol=4)